# Generated by Django 6.0.2 on 2026-03-12 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ITSpecialist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('email', models.EmailField(max_length=254)),
                ('age', models.IntegerField()),
                ('phone', models.CharField(max_length=20)),
                ('birth_date', models.DateField()),
                ('specialization', models.CharField(max_length=50)),
                ('experience', models.PositiveIntegerField()),
                ('position', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('skills', models.TextField()),
                ('salary', models.IntegerField()),
                ('about', models.TextField()),
            ],
        ),
    ]
