# Generated by Django 6.0.2 on 2026-03-02 19:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True)),
                ('name_book', models.CharField(max_length=50, verbose_name='укажите название книги')),
                ('descriptton', models.TextField(verbose_name='укажите описание книги')),
                ('image', models.ImageField(upload_to='books/', verbose_name='загрузите облаку')),
                ('category_book', models.CharField(choices=[('фантастика', 'фантастика'), ('хоррор', 'хоррор'), ('итсорический', 'истороческий')], max_length=100, verbose_name='выберите категории')),
                ('url_audio', models.URLField(verbose_name='укажите ссылку на аудиокнигу')),
            ],
            options={
                'verbose_name': 'книгу',
                'verbose_name_plural': 'книгу',
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_car', models.CharField(max_length=100, verbose_name='укажите название машин')),
                ('brand_model', models.CharField(max_length=100, verbose_name='укажите название модели')),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1886), django.core.validators.MaxValueValidator(2025)], verbose_name='год выпуска')),
                ('color', models.CharField(blank=True, max_length=30, verbose_name='укажите название цвета')),
                ('engine_volume', models.FloatField(verbose_name='укажите обьем двигателя')),
                ('description', models.TextField(null=True, verbose_name='укажите описание машин')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='укажите цену')),
                ('image', models.ImageField(upload_to='cars/', verbose_name='укажите облаку')),
                ('fuel_type', models.CharField(default='Бензин', max_length=20, verbose_name='укжите тип топлива')),
                ('country', models.CharField(max_length=100)),
            ],
        ),
    ]
