# Generated by Django 6.0.2 on 2026-03-05 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars_of_facts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Books',
        ),
    ]
