# Generated by Django 6.0.2 on 2026-03-11 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DriverModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=225)),
                ('photo', models.ImageField(upload_to='Drivers_photos/')),
                ('birth_date', models.DateField()),
                ('car_choice', models.CharField(max_length=100)),
                ('exprience', models.IntegerField()),
                ('has_license', models.BooleanField(default=True)),
            ],
        ),
    ]
